name: Industrialisation continue sur le serveur Alwaysdata
on: 
  push:
    branches:
      - main
jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd $HOME/www/

  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            last_directory=$(basename ${{ runner.workspace }})
            cd $HOME

            # Cloner le repo Git si ce n'est pas déjà fait
            if [ -d ./front ]; then
            rm -rf ./front
            fi
            git clone https://github.com/${{ github.repository }}.git

            # Vérifier si le répertoire www existe et le nettoyer
            if [ -d "./www/" ]; then
              # vérifier si le repertoire flask existe
              if [ -d "./www/flask/" ]; then
                # le déplacer dans out
                mv ./www/flask/ $HOME/${last_directory}/out/
              # else
              #   echo "Le répertoire www/flask/ n'existe pas."
              #   mkdir -p ./www/flask
              fi

              # Supprimer tous les fichiers et répertoires sauf 'out/' et 'flask'

              find ./www/ ! -name 'out' -type d -exec rm -rf {} +
              find ./www/ ! -name 'out' -type f -exec rm -f {} +

              echo "Contenu de www/ nettoyé, préparation du transfert..."

              # ajoute le contenu de out à la racine du site 'out'
              rsync -av --delete $HOME/${last_directory}/out/ ./www/
              
              rm -rf ./front

              echo "Déploiement terminé."

            else
              echo "Le répertoire www/cv n'existe pas sur le serveur."
              exit 1
              # mkdir -p ./www/cv
            fi