name: Industrialisation continue sur le serveur Alwaysdata
on: push
jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd $HOME/www/

  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            last_directory=$(basename ${{ runner.workspace }})
            cd $HOME/www/
            git clone https://github.com/${{ github.repository }}.git

            # Vérifier si le répertoire de destination 'front' existe
            if [ -d "./front" ]; then
              echo "Le répertoire 'front' existe, préparation du transfert..."
              
              # Vérifier si le répertoire 'out' existe dans le dossier cloné
              if [ -d "./${last_directory}/out" ]; then
                # Utiliser rsync pour copier le contenu du dossier 'out' vers './front'
                rsync -av --delete ./${last_directory}/out/ ./front/
                echo "Contenu de 'out' copié avec succès dans 'front'."
                
                # Nettoyer en supprimant le répertoire cloné
                rm -rf ./${last_directory}
              else
                echo "Le répertoire 'out' n'a pas été trouvé dans le répertoire cloné."
                exit 1
              fi
            else
              echo "Le répertoire 'front' de destination n'existe pas sur votre serveur."
              exit 1
            fi

            cd $HOME/www/front
            echo '${{ secrets.MY_SECRET_FILE_CONTENT }}' > .htpasswd
